- !!python/tuple
  - - 0
    - 0
  - 0
- !!python/tuple
  - - 0
    - 1
  - 1
- !!python/tuple
  - - 0
    - 2
  - 2
- !!python/tuple
  - - 0
    - 3
  - 3
- !!python/tuple
  - - 1
    - 3
  - 4
- !!python/tuple
  - - 2
    - 3
  - 5
- !!python/tuple
  - - 2
    - 4
  - 6
- !!python/tuple
  - - 3
    - 4
  - 7
- !!python/tuple
  - - 4
    - 4
  - 8
- !!python/tuple
  - - 5
    - 4
  - 9
- !!python/tuple
  - - 6
    - 4
  - 10
- !!python/tuple
  - - 7
    - 4
  - 11
- !!python/tuple
  - - 8
    - 4
  - 12
- !!python/tuple
  - - 9
    - 4
  - 13
- !!python/tuple
  - - 9
    - 5
  - 14
- !!python/tuple
  - - 9
    - 6
  - 15
- !!python/tuple
  - - 9
    - 7
  - 16
- !!python/tuple
  - &id001
    - 9
    - 8
  - 17
- !!python/tuple
  - *id001
  - 18
- !!python/tuple
  - *id001
  - 19
- !!python/tuple
  - *id001
  - 20
- !!python/tuple
  - - 9
    - 9
  - 21
