dimension: 2
dynamic_obstacles:
- !!python/tuple
  - - 4
    - 28
  - - 29
    - 30
- !!python/tuple
  - - 0
    - 27
  - - 25
    - 26
- !!python/tuple
  - - 16
    - 21
  - - 27
    - 38
- !!python/tuple
  - - 2
    - 26
  - - 19
    - 39
- !!python/tuple
  - - 36
    - 17
  - - 24
    - 32
- !!python/tuple
  - - 38
    - 37
  - - 20
    - 23
- !!python/tuple
  - - 0
    - 37
  - - 15
    - 16
- !!python/tuple
  - - 42
    - 19
  - - 2
    - 24
- !!python/tuple
  - - 11
    - 0
  - - 21
    - 41
- !!python/tuple
  - - 34
    - 47
  - - 24
    - 35
- !!python/tuple
  - - 30
    - 29
  - - 25
    - 38
- !!python/tuple
  - - 14
    - 48
  - - 17
    - 25
- !!python/tuple
  - - 8
    - 36
  - - 24
    - 27
- !!python/tuple
  - - 37
    - 47
  - - 35
    - 42
- !!python/tuple
  - - 25
    - 24
  - - 37
    - 39
- !!python/tuple
  - - 35
    - 31
  - - 22
    - 32
- !!python/tuple
  - - 42
    - 29
  - - 33
    - 37
- !!python/tuple
  - - 5
    - 2
  - - 34
    - 41
- !!python/tuple
  - - 33
    - 43
  - - 31
    - 38
- !!python/tuple
  - - 43
    - 14
  - - 36
    - 38
- !!python/tuple
  - - 0
    - 15
  - - 3
    - 32
- !!python/tuple
  - - 43
    - 9
  - - 21
    - 35
- !!python/tuple
  - - 32
    - 18
  - - 32
    - 32
- !!python/tuple
  - - 38
    - 15
  - - 12
    - 33
- !!python/tuple
  - - 45
    - 14
  - - 41
    - 42
- !!python/tuple
  - - 15
    - 27
  - - 26
    - 37
- !!python/tuple
  - - 49
    - 27
  - - 38
    - 40
- !!python/tuple
  - - 36
    - 8
  - - 7
    - 37
- !!python/tuple
  - - 13
    - 29
  - - 12
    - 33
- !!python/tuple
  - - 42
    - 14
  - - 9
    - 39
- !!python/tuple
  - - 30
    - 22
  - - 2
    - 10
- !!python/tuple
  - - 24
    - 10
  - - 6
    - 22
- !!python/tuple
  - - 10
    - 11
  - - 33
    - 40
- !!python/tuple
  - - 14
    - 21
  - - 1
    - 20
- !!python/tuple
  - - 47
    - 37
  - - 41
    - 42
- !!python/tuple
  - - 17
    - 43
  - - 36
    - 39
- !!python/tuple
  - - 47
    - 27
  - - 4
    - 6
- !!python/tuple
  - - 0
    - 29
  - - 28
    - 35
- !!python/tuple
  - - 2
    - 7
  - - 4
    - 7
- !!python/tuple
  - - 15
    - 34
  - - 26
    - 34
- !!python/tuple
  - - 20
    - 23
  - - 2
    - 16
- !!python/tuple
  - - 28
    - 0
  - - 42
    - 42
- !!python/tuple
  - - 3
    - 47
  - - 31
    - 38
- !!python/tuple
  - - 34
    - 2
  - - 1
    - 8
- !!python/tuple
  - - 26
    - 31
  - - 0
    - 13
- !!python/tuple
  - - 5
    - 38
  - - 24
    - 35
- !!python/tuple
  - - 27
    - 28
  - - 32
    - 42
- !!python/tuple
  - - 41
    - 6
  - - 30
    - 41
- !!python/tuple
  - - 8
    - 40
  - - 31
    - 34
- !!python/tuple
  - - 47
    - 46
  - - 20
    - 25
- !!python/tuple
  - - 5
    - 18
  - - 38
    - 39
- !!python/tuple
  - - 14
    - 5
  - - 38
    - 39
- !!python/tuple
  - - 32
    - 39
  - - 20
    - 34
- !!python/tuple
  - - 23
    - 0
  - - 30
    - 42
- !!python/tuple
  - - 43
    - 1
  - - 38
    - 38
- !!python/tuple
  - - 36
    - 2
  - - 9
    - 35
- !!python/tuple
  - - 44
    - 11
  - - 33
    - 34
- !!python/tuple
  - - 44
    - 18
  - - 4
    - 6
- !!python/tuple
  - - 43
    - 19
  - - 22
    - 34
- !!python/tuple
  - - 46
    - 7
  - - 39
    - 39
- !!python/tuple
  - - 15
    - 32
  - - 30
    - 38
- !!python/tuple
  - - 38
    - 46
  - - 34
    - 35
- !!python/tuple
  - - 23
    - 45
  - - 1
    - 28
- !!python/tuple
  - - 11
    - 30
  - - 14
    - 16
- !!python/tuple
  - - 43
    - 19
  - - 23
    - 30
- !!python/tuple
  - - 24
    - 27
  - - 13
    - 17
- !!python/tuple
  - - 42
    - 38
  - - 22
    - 28
- !!python/tuple
  - - 39
    - 11
  - - 28
    - 31
- !!python/tuple
  - - 17
    - 18
  - - 24
    - 36
- !!python/tuple
  - - 39
    - 3
  - - 37
    - 41
- !!python/tuple
  - - 11
    - 27
  - - 28
    - 35
- !!python/tuple
  - - 31
    - 46
  - - 13
    - 35
- !!python/tuple
  - - 1
    - 19
  - - 20
    - 24
- !!python/tuple
  - - 47
    - 23
  - - 20
    - 25
- !!python/tuple
  - - 40
    - 41
  - - 31
    - 33
- !!python/tuple
  - - 14
    - 31
  - - 12
    - 42
- !!python/tuple
  - - 47
    - 21
  - - 38
    - 42
- !!python/tuple
  - - 15
    - 13
  - - 20
    - 42
- !!python/tuple
  - - 26
    - 8
  - - 23
    - 39
- !!python/tuple
  - - 23
    - 40
  - - 1
    - 35
- !!python/tuple
  - - 43
    - 30
  - - 39
    - 42
- !!python/tuple
  - - 6
    - 8
  - - 5
    - 17
- !!python/tuple
  - - 40
    - 35
  - - 41
    - 41
- !!python/tuple
  - - 44
    - 28
  - - 34
    - 40
- !!python/tuple
  - - 23
    - 34
  - - 9
    - 10
- !!python/tuple
  - - 33
    - 38
  - - 1
    - 37
- !!python/tuple
  - - 45
    - 36
  - - 7
    - 37
- !!python/tuple
  - - 45
    - 43
  - - 38
    - 41
- !!python/tuple
  - - 33
    - 10
  - - 42
    - 42
- !!python/tuple
  - - 37
    - 1
  - - 2
    - 13
- !!python/tuple
  - - 47
    - 32
  - - 25
    - 26
- !!python/tuple
  - - 41
    - 48
  - - 37
    - 38
- !!python/tuple
  - - 12
    - 27
  - - 39
    - 42
- !!python/tuple
  - - 49
    - 11
  - - 19
    - 38
- !!python/tuple
  - - 17
    - 16
  - - 21
    - 39
- !!python/tuple
  - - 2
    - 0
  - - 31
    - 41
- !!python/tuple
  - - 10
    - 45
  - - 16
    - 17
- !!python/tuple
  - - 8
    - 18
  - - 16
    - 37
- !!python/tuple
  - - 33
    - 37
  - - 38
    - 39
- !!python/tuple
  - - 49
    - 46
  - - 34
    - 36
goal_point:
- 7
- 36
space_limits:
- 50
- 50
start_point:
- 14
- 1
static_obstacles:
- - 13
  - 11
- - 41
  - 21
- - 14
  - 29
- - 27
  - 12
- - 38
  - 6
- - 44
  - 24
- - 46
  - 3
- - 32
  - 48
- - 47
  - 22
- - 33
  - 48
- - 36
  - 2
- - 14
  - 29
- - 28
  - 18
- - 17
  - 7
- - 19
  - 42
- - 8
  - 10
- - 31
  - 26
- - 36
  - 14
- - 40
  - 12
- - 28
  - 50
- - 24
  - 46
- - 50
  - 17
- - 32
  - 42
- - 9
  - 25
- - 4
  - 46
- - 45
  - 11
- - 22
  - 3
- - 38
  - 35
- - 16
  - 1
- - 12
  - 33
- - 22
  - 42
- - 45
  - 37
- - 45
  - 50
- - 0
  - 28
- - 36
  - 25
- - 36
  - 43
- - 20
  - 29
- - 38
  - 43
- - 48
  - 26
- - 23
  - 21
- - 40
  - 41
- - 47
  - 28
- - 49
  - 23
- - 30
  - 49
- - 27
  - 8
- - 25
  - 14
- - 40
  - 21
- - 20
  - 18
- - 26
  - 49
- - 10
  - 14
