- !!python/tuple
  - - 22
    - 5
  - 0
- !!python/tuple
  - - 23
    - 5
  - 1
- !!python/tuple
  - - 24
    - 5
  - 2
- !!python/tuple
  - - 25
    - 5
  - 3
- !!python/tuple
  - - 26
    - 5
  - 4
- !!python/tuple
  - - 27
    - 5
  - 5
- !!python/tuple
  - - 28
    - 5
  - 6
- !!python/tuple
  - - 28
    - 6
  - 7
- !!python/tuple
  - - 29
    - 6
  - 8
- !!python/tuple
  - - 30
    - 6
  - 9
- !!python/tuple
  - - 31
    - 6
  - 10
- !!python/tuple
  - - 32
    - 6
  - 11
- !!python/tuple
  - - 33
    - 6
  - 12
- !!python/tuple
  - - 34
    - 6
  - 13
- !!python/tuple
  - - 35
    - 6
  - 14
- !!python/tuple
  - - 36
    - 6
  - 15
- !!python/tuple
  - - 37
    - 6
  - 16
- !!python/tuple
  - - 38
    - 6
  - 17
- !!python/tuple
  - - 39
    - 6
  - 18
- !!python/tuple
  - - 40
    - 6
  - 19
- !!python/tuple
  - - 41
    - 6
  - 20
- !!python/tuple
  - - 42
    - 6
  - 21
- !!python/tuple
  - - 43
    - 6
  - 22
- !!python/tuple
  - - 43
    - 7
  - 23
- !!python/tuple
  - - 44
    - 7
  - 24
- !!python/tuple
  - - 45
    - 7
  - 25
- !!python/tuple
  - - 46
    - 7
  - 26
- !!python/tuple
  - - 47
    - 7
  - 27
- !!python/tuple
  - - 48
    - 7
  - 28
- !!python/tuple
  - - 49
    - 7
  - 29
- !!python/tuple
  - - 50
    - 7
  - 30
- !!python/tuple
  - - 51
    - 7
  - 31
- !!python/tuple
  - - 52
    - 7
  - 32
- !!python/tuple
  - - 53
    - 7
  - 33
- !!python/tuple
  - - 54
    - 7
  - 34
- !!python/tuple
  - - 55
    - 7
  - 35
