dimension: 2
dynamic_obstacles:
- !!python/tuple
  - - 50
    - 12
  - - 4
    - 7
- !!python/tuple
  - - 63
    - 10
  - - 5
    - 32
- !!python/tuple
  - - 23
    - 9
  - - 27
    - 35
- !!python/tuple
  - - 60
    - 6
  - - 5
    - 11
- !!python/tuple
  - - 18
    - 2
  - - 16
    - 33
- !!python/tuple
  - - 54
    - 10
  - - 29
    - 31
- !!python/tuple
  - - 2
    - 12
  - - 15
    - 32
- !!python/tuple
  - - 58
    - 3
  - - 6
    - 7
- !!python/tuple
  - - 22
    - 8
  - - 3
    - 34
- !!python/tuple
  - - 17
    - 7
  - - 7
    - 11
- !!python/tuple
  - - 60
    - 2
  - - 25
    - 34
- !!python/tuple
  - - 34
    - 0
  - - 11
    - 28
- !!python/tuple
  - - 4
    - 8
  - - 17
    - 20
- !!python/tuple
  - - 42
    - 8
  - - 27
    - 32
- !!python/tuple
  - - 10
    - 0
  - - 12
    - 20
- !!python/tuple
  - - 30
    - 3
  - - 21
    - 23
- !!python/tuple
  - - 11
    - 12
  - - 12
    - 31
- !!python/tuple
  - - 2
    - 1
  - - 1
    - 34
- !!python/tuple
  - - 23
    - 7
  - - 5
    - 12
- !!python/tuple
  - - 10
    - 7
  - - 6
    - 18
- !!python/tuple
  - - 1
    - 2
  - - 10
    - 25
- !!python/tuple
  - - 4
    - 11
  - - 2
    - 6
- !!python/tuple
  - - 58
    - 9
  - - 16
    - 28
- !!python/tuple
  - - 41
    - 5
  - - 26
    - 26
- !!python/tuple
  - - 4
    - 12
  - - 11
    - 22
- !!python/tuple
  - - 5
    - 1
  - - 34
    - 34
- !!python/tuple
  - - 5
    - 8
  - - 17
    - 22
- !!python/tuple
  - - 24
    - 4
  - - 7
    - 28
- !!python/tuple
  - - 57
    - 6
  - - 27
    - 27
- !!python/tuple
  - - 46
    - 1
  - - 1
    - 4
- !!python/tuple
  - - 53
    - 11
  - - 15
    - 19
- !!python/tuple
  - - 52
    - 3
  - - 32
    - 35
- !!python/tuple
  - - 61
    - 10
  - - 7
    - 28
- !!python/tuple
  - - 47
    - 11
  - - 19
    - 34
- !!python/tuple
  - - 37
    - 10
  - - 26
    - 28
- !!python/tuple
  - - 33
    - 12
  - - 11
    - 24
- !!python/tuple
  - - 16
    - 2
  - - 35
    - 35
- !!python/tuple
  - - 8
    - 7
  - - 3
    - 16
- !!python/tuple
  - - 44
    - 6
  - - 16
    - 32
- !!python/tuple
  - - 10
    - 1
  - - 10
    - 12
- !!python/tuple
  - - 26
    - 3
  - - 35
    - 35
- !!python/tuple
  - - 32
    - 2
  - - 24
    - 25
- !!python/tuple
  - - 25
    - 10
  - - 26
    - 27
- !!python/tuple
  - - 23
    - 6
  - - 8
    - 14
- !!python/tuple
  - - 13
    - 5
  - - 11
    - 24
- !!python/tuple
  - - 27
    - 11
  - - 30
    - 30
- !!python/tuple
  - - 62
    - 0
  - - 31
    - 34
- !!python/tuple
  - - 34
    - 8
  - - 29
    - 31
- !!python/tuple
  - - 36
    - 10
  - - 1
    - 5
- !!python/tuple
  - - 31
    - 7
  - - 14
    - 33
- !!python/tuple
  - - 27
    - 8
  - - 34
    - 34
- !!python/tuple
  - - 5
    - 10
  - - 13
    - 14
- !!python/tuple
  - - 2
    - 2
  - - 13
    - 19
- !!python/tuple
  - - 6
    - 7
  - - 34
    - 35
- !!python/tuple
  - - 54
    - 12
  - - 3
    - 12
- !!python/tuple
  - - 39
    - 10
  - - 7
    - 33
- !!python/tuple
  - - 33
    - 11
  - - 4
    - 7
- !!python/tuple
  - - 21
    - 7
  - - 28
    - 35
- !!python/tuple
  - - 44
    - 8
  - - 29
    - 31
- !!python/tuple
  - - 21
    - 10
  - - 20
    - 33
- !!python/tuple
  - - 40
    - 1
  - - 34
    - 34
- !!python/tuple
  - - 13
    - 9
  - - 35
    - 35
- !!python/tuple
  - - 47
    - 9
  - - 5
    - 22
- !!python/tuple
  - - 47
    - 3
  - - 5
    - 25
- !!python/tuple
  - - 40
    - 11
  - - 0
    - 9
- !!python/tuple
  - - 51
    - 6
  - - 11
    - 21
- !!python/tuple
  - - 51
    - 8
  - - 8
    - 28
- !!python/tuple
  - - 43
    - 2
  - - 1
    - 33
- !!python/tuple
  - - 23
    - 3
  - - 17
    - 29
- !!python/tuple
  - - 43
    - 2
  - - 34
    - 34
- !!python/tuple
  - - 59
    - 3
  - - 13
    - 33
- !!python/tuple
  - - 55
    - 8
  - - 31
    - 34
- !!python/tuple
  - - 25
    - 8
  - - 26
    - 27
- !!python/tuple
  - - 44
    - 4
  - - 14
    - 26
- !!python/tuple
  - - 36
    - 0
  - - 13
    - 32
- !!python/tuple
  - - 39
    - 8
  - - 26
    - 33
- !!python/tuple
  - - 13
    - 3
  - - 5
    - 33
- !!python/tuple
  - - 50
    - 4
  - - 18
    - 24
- !!python/tuple
  - - 10
    - 6
  - - 8
    - 14
- !!python/tuple
  - - 44
    - 8
  - - 9
    - 24
- !!python/tuple
  - - 39
    - 3
  - - 26
    - 35
- !!python/tuple
  - - 37
    - 0
  - - 28
    - 35
- !!python/tuple
  - - 6
    - 6
  - - 19
    - 34
- !!python/tuple
  - - 22
    - 0
  - - 15
    - 21
- !!python/tuple
  - - 16
    - 7
  - - 14
    - 25
- !!python/tuple
  - - 6
    - 12
  - - 20
    - 28
- !!python/tuple
  - - 45
    - 10
  - - 22
    - 26
- !!python/tuple
  - - 18
    - 10
  - - 13
    - 22
- !!python/tuple
  - - 52
    - 6
  - - 25
    - 27
- !!python/tuple
  - - 46
    - 5
  - - 31
    - 32
- !!python/tuple
  - - 25
    - 5
  - - 34
    - 35
- !!python/tuple
  - - 42
    - 0
  - - 29
    - 34
- !!python/tuple
  - - 36
    - 12
  - - 35
    - 35
- !!python/tuple
  - - 60
    - 2
  - - 25
    - 25
- !!python/tuple
  - - 21
    - 4
  - - 1
    - 22
- !!python/tuple
  - - 27
    - 10
  - - 30
    - 32
- !!python/tuple
  - - 60
    - 6
  - - 8
    - 28
- !!python/tuple
  - - 54
    - 8
  - - 18
    - 34
- !!python/tuple
  - - 50
    - 0
  - - 5
    - 21
- !!python/tuple
  - - 10
    - 3
  - - 30
    - 34
- !!python/tuple
  - - 5
    - 8
  - - 4
    - 25
- !!python/tuple
  - - 39
    - 2
  - - 18
    - 24
- !!python/tuple
  - - 4
    - 9
  - - 29
    - 33
- !!python/tuple
  - - 36
    - 8
  - - 11
    - 15
- !!python/tuple
  - - 18
    - 5
  - - 6
    - 24
- !!python/tuple
  - - 40
    - 7
  - - 4
    - 19
- !!python/tuple
  - - 27
    - 0
  - - 21
    - 23
- !!python/tuple
  - - 36
    - 2
  - - 7
    - 12
- !!python/tuple
  - - 54
    - 1
  - - 26
    - 27
- !!python/tuple
  - - 24
    - 9
  - - 7
    - 11
- !!python/tuple
  - - 39
    - 6
  - - 9
    - 12
- !!python/tuple
  - - 0
    - 8
  - - 9
    - 33
- !!python/tuple
  - - 58
    - 0
  - - 22
    - 23
- !!python/tuple
  - - 23
    - 3
  - - 2
    - 33
- !!python/tuple
  - - 23
    - 8
  - - 4
    - 33
- !!python/tuple
  - - 63
    - 11
  - - 28
    - 29
- !!python/tuple
  - - 13
    - 9
  - - 31
    - 32
- !!python/tuple
  - - 16
    - 7
  - - 27
    - 34
- !!python/tuple
  - - 47
    - 5
  - - 18
    - 21
- !!python/tuple
  - - 48
    - 1
  - - 9
    - 31
- !!python/tuple
  - - 54
    - 4
  - - 24
    - 33
- !!python/tuple
  - - 50
    - 8
  - - 1
    - 30
- !!python/tuple
  - - 63
    - 7
  - - 31
    - 35
- !!python/tuple
  - - 53
    - 10
  - - 12
    - 27
- !!python/tuple
  - - 1
    - 4
  - - 32
    - 35
- !!python/tuple
  - - 63
    - 8
  - - 34
    - 34
- !!python/tuple
  - - 63
    - 1
  - - 20
    - 25
- !!python/tuple
  - - 38
    - 3
  - - 26
    - 30
- !!python/tuple
  - - 43
    - 1
  - - 23
    - 29
- !!python/tuple
  - - 49
    - 2
  - - 2
    - 8
- !!python/tuple
  - - 31
    - 9
  - - 2
    - 25
- !!python/tuple
  - - 18
    - 9
  - - 23
    - 31
- !!python/tuple
  - - 55
    - 11
  - - 14
    - 17
- !!python/tuple
  - - 57
    - 0
  - - 28
    - 28
- !!python/tuple
  - - 5
    - 9
  - - 33
    - 34
- !!python/tuple
  - - 34
    - 8
  - - 13
    - 14
- !!python/tuple
  - - 18
    - 12
  - - 4
    - 25
- !!python/tuple
  - - 27
    - 10
  - - 26
    - 29
- !!python/tuple
  - - 61
    - 0
  - - 5
    - 6
- !!python/tuple
  - - 34
    - 5
  - - 4
    - 31
- !!python/tuple
  - - 62
    - 5
  - - 14
    - 35
- !!python/tuple
  - - 30
    - 6
  - - 30
    - 35
- !!python/tuple
  - - 60
    - 12
  - - 11
    - 20
- !!python/tuple
  - - 61
    - 9
  - - 3
    - 4
- !!python/tuple
  - - 9
    - 6
  - - 29
    - 35
- !!python/tuple
  - - 19
    - 5
  - - 21
    - 33
- !!python/tuple
  - - 63
    - 6
  - - 23
    - 25
- !!python/tuple
  - - 24
    - 11
  - - 29
    - 34
- !!python/tuple
  - - 32
    - 12
  - - 21
    - 24
- !!python/tuple
  - - 34
    - 10
  - - 13
    - 29
- !!python/tuple
  - - 23
    - 3
  - - 1
    - 27
- !!python/tuple
  - - 15
    - 4
  - - 35
    - 35
- !!python/tuple
  - - 48
    - 1
  - - 4
    - 29
- !!python/tuple
  - - 2
    - 6
  - - 27
    - 34
- !!python/tuple
  - - 33
    - 10
  - - 20
    - 32
- !!python/tuple
  - - 35
    - 4
  - - 20
    - 26
- !!python/tuple
  - - 56
    - 4
  - - 16
    - 23
- !!python/tuple
  - - 57
    - 5
  - - 19
    - 25
- !!python/tuple
  - - 2
    - 4
  - - 13
    - 30
- !!python/tuple
  - - 30
    - 8
  - - 22
    - 26
- !!python/tuple
  - - 29
    - 5
  - - 2
    - 27
- !!python/tuple
  - - 43
    - 6
  - - 29
    - 34
- !!python/tuple
  - - 7
    - 11
  - - 11
    - 30
- !!python/tuple
  - - 21
    - 1
  - - 28
    - 30
- !!python/tuple
  - - 37
    - 11
  - - 16
    - 24
- !!python/tuple
  - - 58
    - 7
  - - 26
    - 32
- !!python/tuple
  - - 8
    - 9
  - - 30
    - 30
- !!python/tuple
  - - 59
    - 2
  - - 25
    - 26
- !!python/tuple
  - - 63
    - 4
  - - 27
    - 27
- !!python/tuple
  - - 40
    - 4
  - - 22
    - 22
- !!python/tuple
  - - 42
    - 3
  - - 25
    - 31
- !!python/tuple
  - - 61
    - 12
  - - 24
    - 29
- !!python/tuple
  - - 14
    - 0
  - - 11
    - 31
- !!python/tuple
  - - 58
    - 1
  - - 20
    - 32
- !!python/tuple
  - - 58
    - 12
  - - 21
    - 26
- !!python/tuple
  - - 18
    - 12
  - - 7
    - 8
- !!python/tuple
  - - 37
    - 7
  - - 12
    - 26
- !!python/tuple
  - - 17
    - 5
  - - 15
    - 23
- !!python/tuple
  - - 37
    - 4
  - - 29
    - 34
- !!python/tuple
  - - 55
    - 4
  - - 1
    - 33
- !!python/tuple
  - - 7
    - 1
  - - 26
    - 31
- !!python/tuple
  - - 10
    - 7
  - - 23
    - 26
- !!python/tuple
  - - 0
    - 10
  - - 6
    - 8
- !!python/tuple
  - - 29
    - 9
  - - 21
    - 34
- !!python/tuple
  - - 4
    - 3
  - - 2
    - 29
- !!python/tuple
  - - 52
    - 7
  - - 9
    - 29
- !!python/tuple
  - - 49
    - 6
  - - 27
    - 33
- !!python/tuple
  - - 0
    - 9
  - - 31
    - 35
- !!python/tuple
  - - 53
    - 9
  - - 9
    - 9
- !!python/tuple
  - - 6
    - 0
  - - 34
    - 34
- !!python/tuple
  - - 30
    - 4
  - - 15
    - 24
- !!python/tuple
  - - 9
    - 4
  - - 27
    - 28
- !!python/tuple
  - - 39
    - 5
  - - 22
    - 35
- !!python/tuple
  - - 18
    - 5
  - - 30
    - 35
- !!python/tuple
  - - 11
    - 8
  - - 29
    - 32
- !!python/tuple
  - - 6
    - 1
  - - 16
    - 21
- !!python/tuple
  - - 40
    - 0
  - - 9
    - 24
- !!python/tuple
  - - 40
    - 11
  - - 21
    - 29
- !!python/tuple
  - - 43
    - 8
  - - 23
    - 32
- !!python/tuple
  - - 52
    - 10
  - - 33
    - 33
- !!python/tuple
  - - 54
    - 2
  - - 15
    - 24
- !!python/tuple
  - - 60
    - 11
  - - 21
    - 34
- !!python/tuple
  - - 54
    - 2
  - - 24
    - 28
- !!python/tuple
  - - 21
    - 9
  - - 17
    - 26
- !!python/tuple
  - - 21
    - 11
  - - 5
    - 24
- !!python/tuple
  - - 6
    - 12
  - - 25
    - 32
- !!python/tuple
  - - 44
    - 3
  - - 0
    - 14
- !!python/tuple
  - - 10
    - 1
  - - 31
    - 31
- !!python/tuple
  - - 18
    - 5
  - - 19
    - 27
- !!python/tuple
  - - 62
    - 12
  - - 7
    - 8
- !!python/tuple
  - - 60
    - 1
  - - 25
    - 30
- !!python/tuple
  - - 13
    - 3
  - - 23
    - 34
- !!python/tuple
  - - 13
    - 8
  - - 14
    - 35
- !!python/tuple
  - - 11
    - 8
  - - 13
    - 29
- !!python/tuple
  - - 3
    - 0
  - - 12
    - 16
- !!python/tuple
  - - 40
    - 12
  - - 31
    - 35
- !!python/tuple
  - - 19
    - 12
  - - 27
    - 35
- !!python/tuple
  - - 40
    - 4
  - - 2
    - 6
- !!python/tuple
  - - 25
    - 1
  - - 30
    - 34
- !!python/tuple
  - - 28
    - 9
  - - 3
    - 17
- !!python/tuple
  - - 24
    - 3
  - - 9
    - 14
- !!python/tuple
  - - 12
    - 2
  - - 8
    - 27
- !!python/tuple
  - - 8
    - 0
  - - 13
    - 18
- !!python/tuple
  - - 30
    - 11
  - - 34
    - 35
- !!python/tuple
  - - 6
    - 3
  - - 16
    - 33
- !!python/tuple
  - - 54
    - 9
  - - 15
    - 16
- !!python/tuple
  - - 6
    - 12
  - - 27
    - 33
- !!python/tuple
  - - 12
    - 6
  - - 34
    - 34
- !!python/tuple
  - - 8
    - 5
  - - 11
    - 31
- !!python/tuple
  - - 12
    - 9
  - - 33
    - 33
- !!python/tuple
  - - 31
    - 9
  - - 0
    - 29
- !!python/tuple
  - - 60
    - 6
  - - 6
    - 14
- !!python/tuple
  - - 43
    - 10
  - - 8
    - 13
- !!python/tuple
  - - 42
    - 12
  - - 25
    - 31
goal_point:
- 55
- 7
space_limits:
- 64
- 13
start_point:
- 22
- 5
static_obstacles:
- - 1
  - 1
- - 2
  - 2
- - 3
  - 3
