dimension: 2
dynamic_obstacles:
- !!python/tuple
  - - 19
    - 8
  - - 18
    - 63
- !!python/tuple
  - - 28
    - 25
  - - 15
    - 18
- !!python/tuple
  - - 26
    - 33
  - - 60
    - 68
- !!python/tuple
  - - 18
    - 47
  - - 22
    - 67
- !!python/tuple
  - - 25
    - 47
  - - 52
    - 55
- !!python/tuple
  - - 20
    - 15
  - - 34
    - 48
- !!python/tuple
  - - 42
    - 45
  - - 50
    - 59
- !!python/tuple
  - - 29
    - 27
  - - 8
    - 68
- !!python/tuple
  - - 49
    - 33
  - - 73
    - 73
- !!python/tuple
  - - 34
    - 2
  - - 29
    - 33
- !!python/tuple
  - - 45
    - 30
  - - 40
    - 46
- !!python/tuple
  - - 14
    - 46
  - - 30
    - 69
- !!python/tuple
  - - 30
    - 14
  - - 77
    - 77
- !!python/tuple
  - - 18
    - 49
  - - 43
    - 65
- !!python/tuple
  - - 36
    - 25
  - - 5
    - 21
- !!python/tuple
  - - 35
    - 9
  - - 17
    - 67
- !!python/tuple
  - - 26
    - 10
  - - 43
    - 64
- !!python/tuple
  - - 22
    - 20
  - - 2
    - 60
- !!python/tuple
  - - 44
    - 31
  - - 70
    - 76
- !!python/tuple
  - - 4
    - 27
  - - 35
    - 41
- !!python/tuple
  - - 17
    - 5
  - - 77
    - 77
- !!python/tuple
  - - 21
    - 36
  - - 45
    - 53
- !!python/tuple
  - - 44
    - 18
  - - 21
    - 70
- !!python/tuple
  - - 35
    - 41
  - - 64
    - 71
- !!python/tuple
  - - 38
    - 30
  - - 50
    - 59
- !!python/tuple
  - - 36
    - 29
  - - 8
    - 37
- !!python/tuple
  - - 14
    - 37
  - - 9
    - 57
- !!python/tuple
  - - 48
    - 47
  - - 17
    - 39
- !!python/tuple
  - - 40
    - 8
  - - 43
    - 45
- !!python/tuple
  - - 21
    - 46
  - - 44
    - 75
- !!python/tuple
  - - 23
    - 1
  - - 66
    - 69
- !!python/tuple
  - - 16
    - 22
  - - 11
    - 53
- !!python/tuple
  - - 6
    - 17
  - - 76
    - 76
- !!python/tuple
  - - 20
    - 38
  - - 19
    - 20
- !!python/tuple
  - - 47
    - 9
  - - 74
    - 75
- !!python/tuple
  - - 48
    - 15
  - - 55
    - 76
- !!python/tuple
  - - 40
    - 48
  - - 65
    - 66
- !!python/tuple
  - - 9
    - 28
  - - 22
    - 23
- !!python/tuple
  - - 7
    - 32
  - - 28
    - 48
- !!python/tuple
  - - 43
    - 12
  - - 62
    - 63
- !!python/tuple
  - - 27
    - 16
  - - 3
    - 38
- !!python/tuple
  - - 46
    - 14
  - - 22
    - 33
- !!python/tuple
  - - 8
    - 3
  - - 76
    - 77
- !!python/tuple
  - - 25
    - 15
  - - 65
    - 73
- !!python/tuple
  - - 39
    - 0
  - - 33
    - 70
- !!python/tuple
  - - 1
    - 28
  - - 51
    - 66
- !!python/tuple
  - - 44
    - 23
  - - 57
    - 63
- !!python/tuple
  - - 12
    - 5
  - - 5
    - 12
- !!python/tuple
  - - 23
    - 25
  - - 17
    - 58
- !!python/tuple
  - - 1
    - 36
  - - 27
    - 31
- !!python/tuple
  - - 39
    - 31
  - - 1
    - 4
- !!python/tuple
  - - 12
    - 3
  - - 54
    - 72
- !!python/tuple
  - - 26
    - 40
  - - 60
    - 75
- !!python/tuple
  - - 49
    - 3
  - - 54
    - 60
- !!python/tuple
  - - 13
    - 32
  - - 61
    - 67
- !!python/tuple
  - - 47
    - 6
  - - 66
    - 76
- !!python/tuple
  - - 27
    - 21
  - - 28
    - 38
- !!python/tuple
  - - 5
    - 9
  - - 57
    - 68
- !!python/tuple
  - - 49
    - 36
  - - 76
    - 76
- !!python/tuple
  - - 33
    - 46
  - - 13
    - 56
- !!python/tuple
  - - 11
    - 0
  - - 13
    - 62
- !!python/tuple
  - - 22
    - 25
  - - 66
    - 73
- !!python/tuple
  - - 15
    - 42
  - - 40
    - 40
- !!python/tuple
  - - 29
    - 7
  - - 0
    - 17
- !!python/tuple
  - - 45
    - 22
  - - 15
    - 76
- !!python/tuple
  - - 23
    - 15
  - - 21
    - 26
- !!python/tuple
  - - 17
    - 28
  - - 44
    - 76
- !!python/tuple
  - - 18
    - 26
  - - 15
    - 28
- !!python/tuple
  - - 27
    - 39
  - - 52
    - 65
- !!python/tuple
  - - 20
    - 29
  - - 35
    - 49
- !!python/tuple
  - - 25
    - 5
  - - 45
    - 61
- !!python/tuple
  - - 44
    - 11
  - - 20
    - 69
- !!python/tuple
  - - 9
    - 0
  - - 17
    - 26
- !!python/tuple
  - - 3
    - 28
  - - 9
    - 16
- !!python/tuple
  - - 28
    - 33
  - - 51
    - 72
- !!python/tuple
  - - 27
    - 34
  - - 53
    - 77
- !!python/tuple
  - - 7
    - 26
  - - 65
    - 68
- !!python/tuple
  - - 2
    - 13
  - - 37
    - 66
- !!python/tuple
  - - 3
    - 32
  - - 31
    - 40
- !!python/tuple
  - - 8
    - 44
  - - 35
    - 46
- !!python/tuple
  - - 7
    - 24
  - - 38
    - 47
- !!python/tuple
  - - 39
    - 1
  - - 12
    - 41
- !!python/tuple
  - - 46
    - 45
  - - 46
    - 50
- !!python/tuple
  - - 44
    - 37
  - - 59
    - 73
- !!python/tuple
  - - 48
    - 14
  - - 36
    - 42
- !!python/tuple
  - - 18
    - 10
  - - 41
    - 43
- !!python/tuple
  - - 26
    - 24
  - - 48
    - 75
- !!python/tuple
  - - 13
    - 26
  - - 17
    - 34
- !!python/tuple
  - - 12
    - 1
  - - 25
    - 68
- !!python/tuple
  - - 18
    - 41
  - - 76
    - 76
- !!python/tuple
  - - 43
    - 38
  - - 2
    - 7
- !!python/tuple
  - - 35
    - 34
  - - 10
    - 33
- !!python/tuple
  - - 9
    - 5
  - - 16
    - 72
- !!python/tuple
  - - 11
    - 45
  - - 21
    - 21
- !!python/tuple
  - - 47
    - 36
  - - 30
    - 77
- !!python/tuple
  - - 0
    - 39
  - - 28
    - 68
- !!python/tuple
  - - 39
    - 46
  - - 9
    - 12
- !!python/tuple
  - - 38
    - 38
  - - 7
    - 59
- !!python/tuple
  - - 31
    - 5
  - - 1
    - 54
- !!python/tuple
  - - 0
    - 7
  - - 39
    - 68
goal_points:
- - 5
  - 47
- - 42
  - 9
- - 33
  - 0
- - 47
  - 35
- - 3
  - 32
- - 32
  - 48
- - 11
  - 26
- - 19
  - 12
- - 32
  - 43
- - 29
  - 43
space_limits:
- 50
- 50
start_points:
- - 46
  - 46
- - 25
  - 5
- - 0
  - 44
- - 48
  - 36
- - 35
  - 36
- - 8
  - 18
- - 10
  - 39
- - 3
  - 38
- - 24
  - 6
- - 28
  - 44
static_obstacles:
- - 9
  - 5
- - 10
  - 6
- - 46
  - 10
- - 46
  - 24
- - 49
  - 25
- - 19
  - 49
- - 21
  - 6
- - 32
  - 12
- - 13
  - 42
- - 8
  - 23
- - 7
  - 36
- - 3
  - 3
- - 21
  - 17
- - 2
  - 44
- - 14
  - 36
- - 31
  - 40
- - 46
  - 20
- - 11
  - 6
- - 42
  - 49
- - 29
  - 6
- - 29
  - 44
- - 18
  - 43
- - 24
  - 24
- - 34
  - 40
- - 39
  - 23
- - 0
  - 24
- - 47
  - 19
- - 36
  - 30
- - 43
  - 18
- - 22
  - 27
- - 37
  - 38
- - 44
  - 30
- - 45
  - 45
- - 28
  - 24
- - 10
  - 6
- - 44
  - 35
- - 40
  - 7
- - 46
  - 4
- - 36
  - 0
- - 26
  - 28
- - 28
  - 0
- - 13
  - 33
- - 21
  - 1
- - 19
  - 37
- - 4
  - 25
- - 43
  - 5
- - 16
  - 25
- - 15
  - 13
- - 2
  - 16
- - 38
  - 29
