dimension: 2
dynamic_obstacles:
- !!python/tuple
  - - 8
    - 6
  - - 3
    - 3
- !!python/tuple
  - - 9
    - 2
  - - 8
    - 11
- !!python/tuple
  - - 6
    - 6
  - - 0
    - 3
- !!python/tuple
  - - 6
    - 6
  - - 5
    - 7
- !!python/tuple
  - - 7
    - 3
  - - 7
    - 7
- !!python/tuple
  - - 1
    - 3
  - - 4
    - 8
- !!python/tuple
  - - 4
    - 5
  - - 8
    - 11
- !!python/tuple
  - - 1
    - 1
  - - 12
    - 12
- !!python/tuple
  - - 8
    - 8
  - - 2
    - 8
goal_points:
- - 2
  - 6
- - 7
  - 5
- - 5
  - 1
- - 4
  - 2
- - 0
  - 3
- - 6
  - 4
- - 5
  - 5
- - 1
  - 0
- - 8
  - 4
- - 8
  - 4
space_limits:
- 10
- 10
start_points:
- - 2
  - 1
- - 5
  - 9
- - 9
  - 9
- - 6
  - 7
- - 6
  - 8
- - 9
  - 9
- - 6
  - 7
- - 7
  - 4
- - 2
  - 6
- - 1
  - 9
static_obstacles:
- - 6
  - 2
- - 4
  - 1
- - 6
  - 6
- - 9
  - 7
- - 9
  - 5
