dimension: 2
dynamic_obstacles: []
goal_points:
- - 14
  - 13
- - 14
  - 47
- - 39
  - 34
- - 45
  - 24
- - 49
  - 40
- - 32
  - 49
- - 40
  - 23
- - 40
  - 26
- - 7
  - 43
- - 33
  - 49
- - 9
  - 44
- - 35
  - 29
- - 15
  - 4
- - 15
  - 1
- - 39
  - 38
- - 38
  - 6
- - 3
  - 6
- - 27
  - 34
- - 48
  - 39
- - 39
  - 40
- - 21
  - 33
- - 17
  - 9
- - 48
  - 16
- - 15
  - 15
- - 9
  - 5
- - 14
  - 20
- - 0
  - 49
- - 19
  - 46
- - 19
  - 29
- - 49
  - 8
- - 32
  - 30
- - 29
  - 7
- - 22
  - 38
- - 39
  - 16
- - 39
  - 12
- - 19
  - 13
- - 19
  - 18
- - 12
  - 37
- - 16
  - 23
- - 15
  - 19
space_limits:
- 50
- 50
start_points:
- - 13
  - 6
- - 29
  - 20
- - 9
  - 38
- - 31
  - 37
- - 6
  - 2
- - 35
  - 22
- - 35
  - 27
- - 18
  - 31
- - 1
  - 27
- - 5
  - 36
- - 48
  - 34
- - 12
  - 28
- - 26
  - 40
- - 22
  - 13
- - 46
  - 43
- - 10
  - 9
- - 22
  - 29
- - 37
  - 49
- - 11
  - 27
- - 31
  - 21
- - 32
  - 48
- - 36
  - 36
- - 49
  - 25
- - 25
  - 46
- - 34
  - 21
- - 28
  - 36
- - 17
  - 33
- - 34
  - 9
- - 47
  - 3
- - 35
  - 5
- - 9
  - 10
- - 24
  - 19
- - 48
  - 38
- - 49
  - 6
- - 35
  - 23
- - 44
  - 18
- - 4
  - 45
- - 31
  - 32
- - 49
  - 45
- - 44
  - 36
static_obstacles: []
