dimension: 2
dynamic_obstacles: []
goal_points:
- - 2
  - 21
- - 20
  - 27
- - 1
  - 0
- - 2
  - 39
- - 36
  - 7
- - 38
  - 19
- - 47
  - 7
- - 6
  - 0
- - 39
  - 12
- - 41
  - 10
- - 28
  - 11
- - 7
  - 34
- - 10
  - 43
- - 0
  - 26
- - 32
  - 9
- - 20
  - 39
- - 24
  - 41
- - 4
  - 17
- - 11
  - 23
- - 22
  - 29
- - 27
  - 22
- - 34
  - 37
- - 22
  - 7
- - 0
  - 15
- - 12
  - 36
- - 44
  - 0
- - 26
  - 3
- - 9
  - 47
- - 47
  - 48
- - 30
  - 13
space_limits:
- 50
- 50
start_points:
- - 32
  - 14
- - 29
  - 2
- - 43
  - 48
- - 19
  - 12
- - 39
  - 30
- - 38
  - 13
- - 7
  - 3
- - 7
  - 10
- - 21
  - 7
- - 7
  - 38
- - 7
  - 7
- - 49
  - 1
- - 24
  - 17
- - 8
  - 20
- - 29
  - 27
- - 39
  - 21
- - 49
  - 48
- - 25
  - 27
- - 45
  - 14
- - 15
  - 19
- - 27
  - 8
- - 9
  - 48
- - 2
  - 25
- - 5
  - 15
- - 42
  - 42
- - 24
  - 1
- - 2
  - 12
- - 47
  - 41
- - 0
  - 2
- - 1
  - 28
static_obstacles: []
