dimension: 2
dynamic_obstacles:
- !!python/tuple
  - - 13
    - 13
  - - 1
    - 18
- !!python/tuple
  - - 1
    - 15
  - - 13
    - 13
- !!python/tuple
  - - 18
    - 3
  - - 2
    - 26
- !!python/tuple
  - - 18
    - 1
  - - 16
    - 16
- !!python/tuple
  - - 6
    - 7
  - - 17
    - 17
- !!python/tuple
  - - 12
    - 18
  - - 21
    - 25
- !!python/tuple
  - - 3
    - 8
  - - 7
    - 17
- !!python/tuple
  - - 18
    - 17
  - - 24
    - 25
- !!python/tuple
  - - 17
    - 13
  - - 12
    - 20
goal_points:
- - 4
  - 12
- - 13
  - 3
- - 11
  - 19
- - 7
  - 12
- - 2
  - 13
- - 5
  - 10
- - 8
  - 18
- - 17
  - 14
- - 18
  - 2
- - 3
  - 19
space_limits:
- 20
- 20
start_points:
- - 11
  - 11
- - 13
  - 10
- - 18
  - 12
- - 12
  - 6
- - 16
  - 1
- - 9
  - 12
- - 2
  - 9
- - 14
  - 16
- - 6
  - 1
- - 19
  - 18
static_obstacles:
- - 13
  - 19
- - 13
  - 13
- - 5
  - 17
- - 3
  - 4
- - 9
  - 14
